# Python Exercises - Granger's Elf Analysis

Dr. Granger is interested in studying the relationship between the length of house-elves’ ears and aspects of their DNA. This research is part of a larger project attempting to understand why house-elves possess such powerful magic. She has obtained DNA samples and ear measurements from a small group of house-elves to conduct a preliminary analysis (prior to submitting a grant application to the Ministry of Magic) and she would like you to conduct the analysis for her. She has placed the file on the web for you to download, located ==> [here]( https://nyu-cds.github.io/courses/data/houseelf_earlength_dna_data.csv ) <==.

You might be able to do this analysis by hand in Excel, but counting all of those bases would be a lot of work, and besides, Dr. Granger seems to always get funded, which means that you’ll be doing this again soon with a much larger dataset. So, you decide to write a script so that it will be easy to do the analysis again.

Write a Python script that:

1. Imports the data into a data frame
2. Loops over the rows in the data frame
3. For each row in the dataset, checks to see if the ear length is large (>10 cm) or small (<=10 cm) and determines the GC-content of the DNA sequence (i.e., the percentage of bases that are either G or C)
4. Stores this information in a **new data frame** where the first column has the ID for the individual, the second column contains the string ‘large’ or the string ‘small’ depending on the size of the individuals ears, and the third column contains the GC content of the DNA sequence.
5. Prints the average GC-content for both large-eared elves and small-eared elves to the screen.
6. Exports the table of individual level GC values to a CSV (comma delimited text) file titled grangers_analysis.csv.

**BONUS**: Write functions that perform each of the steps above

[Source for problem](https://nyu-cds.github.io/courses/exercises/Basic-python-2/)

# Solution - variant 1

Load in the modules

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = 'https://nyu-cds.github.io/courses/data/houseelf_earlength_dna_data.csv'
url

'https://nyu-cds.github.io/courses/data/houseelf_earlength_dna_data.csv'

### Request 1:

Imports the data into a data frame

In [ ]:
# Load the data natively from your Drive
df = pd.read_csv( url )
df

    id  earlength                                             dnaseq
0  17A        5.1  CCGCATCTTGACTTAACTGACATATTACCATAGATGACTAGCCATG...
1  24P        7.5  GCTATGACTTGCTTAGCTACGTATGAAGGAAGAAACTTTTGTGTAT...
2  09Q       12.2  CCGCCGATTGATACAGGGGACGGTGACGTCGTCATAGATTCGGCAC...
3  65Y        9.9  GCAGGAGAAGTTCTTAACCTTCTCGTAGGACGTCAACCTATTCTTT...
4  19N       10.0  TCTTCATCCTTATCAAAGTTTGGAGTCAATGATCAGGATTATTGCC...
5  92K       14.6  ACCGATGGACAATGATTCGGGTAGCACCAGGAGTCCGTAGCGCGTG...
6  33W        8.2  CAGCTTGACTCGGTCTGTTAGGCCACGATTACGTGAGTTAGGGCTC...
7  98C       17.8  CTGCATGCTAGGTTGACACGCCTGCACTGCTCGAAGAAAATATGCG...
8  75G        9.4  CTTATTTAGATAACATGATTAGCCGAAGTTGTACGGGATATCCACC...
9  88Q       11.3  GATTGCTCGCACATGAGCAAAACGGTAGAGCGTCACTTTCAGCCCT...

In [ ]:
df.shape

(10, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     object
 1   earlength  10 non-null     float64
 2   dnaseq     10 non-null     object
dtypes: float64(1), object(2)
memory usage: 372.0+ bytes

In [ ]:
df.describe()

       earlength
count   10.00000
mean    10.60000
std      3.63318
min      5.10000
25%      8.50000
50%      9.95000
75%     11.97500
max     17.80000

### Request 2 and 3:

Loops over the rows in the data frame - This was replaced with two function: one of the functions calculates the GC content, the other function converts the length of the ears in a string, large or small depending on the size.


For each row in the dataset, checks to see if the ear length is large (>10 cm) or small (<=10 cm) and determines the GC-content of the DNA sequence (i.e., the percentage of bases that are either G or C)

In [ ]:
# a vectorized approach
# this uses a regular expression in the .count() method
df['gc_content'] = df["dnaseq"].str.count(r'[GC]')/df["dnaseq"].str.len()*100
df

,id,earlength,dnaseq,gc_content
0,17A,5.1,CCGCATCTTGACTTAACTGACATATTACCATAGATGACTAGCCATG...,41.0
1,24P,7.5,GCTATGACTTGCTTAGCTACGTATGAAGGAAGAAACTTTTGTGTAT...,39.0
2,09Q,12.2,CCGCCGATTGATACAGGGGACGGTGACGTCGTCATAGATTCGGCAC...,57.0
3,65Y,9.9,GCAGGAGAAGTTCTTAACCTTCTCGTAGGACGTCAACCTATTCTTT...,40.0
4,19N,10.0,TCTTCATCCTTATCAAAGTTTGGAGTCAATGATCAGGATTATTGCC...,36.0
5,92K,14.6,ACCGATGGACAATGATTCGGGTAGCACCAGGAGTCCGTAGCGCGTG...,62.0
6,33W,8.2,CAGCTTGACTCGGTCTGTTAGGCCACGATTACGTGAGTTAGGGCTC...,52.0
7,98C,17.8,CTGCATGCTAGGTTGACACGCCTGCACTGCTCGAAGAAAATATGCG...,63.0
8,75G,9.4,CTTATTTAGATAACATGATTAGCCGAAGTTGTACGGGATATCCACC...,47.0
9,88Q,11.3,GATTGCTCGCACATGAGCAAAACGGTAGAGCGTCACTTTCAGCCCT...,52.0

In [ ]:
# a vectorized approach
# uses numpy's .where() method
df['ear_size'] = np.where(df['earlength'] > 10, 'high', 'low')
df

,id,earlength,dnaseq,gc_content,ear_size
0,17A,5.1,CCGCATCTTGACTTAACTGACATATTACCATAGATGACTAGCCATG...,41.0,low
1,24P,7.5,GCTATGACTTGCTTAGCTACGTATGAAGGAAGAAACTTTTGTGTAT...,39.0,low
2,09Q,12.2,CCGCCGATTGATACAGGGGACGGTGACGTCGTCATAGATTCGGCAC...,57.0,high
3,65Y,9.9,GCAGGAGAAGTTCTTAACCTTCTCGTAGGACGTCAACCTATTCTTT...,40.0,low
4,19N,10.0,TCTTCATCCTTATCAAAGTTTGGAGTCAATGATCAGGATTATTGCC...,36.0,low
5,92K,14.6,ACCGATGGACAATGATTCGGGTAGCACCAGGAGTCCGTAGCGCGTG...,62.0,high
6,33W,8.2,CAGCTTGACTCGGTCTGTTAGGCCACGATTACGTGAGTTAGGGCTC...,52.0,low
7,98C,17.8,CTGCATGCTAGGTTGACACGCCTGCACTGCTCGAAGAAAATATGCG...,63.0,high
8,75G,9.4,CTTATTTAGATAACATGATTAGCCGAAGTTGTACGGGATATCCACC...,47.0,low
9,88Q,11.3,GATTGCTCGCACATGAGCAAAACGGTAGAGCGTCACTTTCAGCCCT...,52.0,high

### Request 4:

Stores this information in a new data frame where the first column has the ID for the individual, the second column contains the string ‘large’ or the string ‘small’ depending on the size of the individuals ears, and the third column contains the GC content of the DNA sequence.

In [ ]:
#creating a new df with only the information I need
grangers_df = df[['id', 'ear_size', 'gc_content']].copy()
grangers_df

    id ear_size  gc_content
0  17A      low        41.0
1  24P      low        39.0
2  09Q     high        57.0
3  65Y      low        40.0
4  19N      low        36.0
5  92K     high        62.0
6  33W      low        52.0
7  98C     high        63.0
8  75G      low        47.0
9  88Q     high        52.0

### Request 5:

Prints the average GC-content for both large-eared elves and small-eared elves to the screen.

In [ ]:
# Group by the ear size and calculate the average GC content
# renames the series and converts to a data frame
grangers_df.groupby('ear_size')['gc_content'].mean().rename("mean GC content").reset_index()

  ear_size  mean GC content
0     high             58.5
1      low             42.5

### Request 6:


Exports the table of individual level GC values to a CSV (comma delimited text) file titled grangers_analysis.csv.

In [ ]:
# It saves the file directly to working directory in Colab
grangers_df.to_csv('grangers_analysis.csv', index=False)
print("\nFile successfully exported as 'grangers_analysis.csv'")

File successfully exported as 'grangers_analysis.csv'

Verify that the CSV file exists.

In [ ]:
!ls -la granger*

-rw-r--r-- 1 root root 170 May 26 00:42 grangers_analysis.csv

In [ ]:
!cat -n granger*

     1	id,ear_size,gc_content
     2	17A,low,41.0
     3	24P,low,39.0
     4	09Q,high,56.99999999999999
     5	65Y,low,40.0
     6	19N,low,36.0
     7	92K,high,62.0
     8	33W,low,52.0
     9	98C,high,63.0
    10	75G,low,47.0
    11	88Q,high,52.0

In [ ]:
from google.colab import drive
drive.mount('/content')

In [ ]:
# to save the file into my Google drive:
out_csv = "/content/drive/MyDrive/ddds-cohort-20/Modules/Module_3_SQL/Exercises/grangers_analysis.csv"

grangers_df.to_csv( out_csv, index=False)
print("\nFile successfully exported as '/content/drive/MyDrive/ddds-cohort-20/Modules/Module_3_SQL/Exercises/grangers_analysis.csv'")