# Python Exercises - Granger's Elf Analysis

Dr. Granger is interested in studying the relationship between the length of house-elves’ ears and aspects of their DNA. This research is part of a larger project attempting to understand why house-elves possess such powerful magic. She has obtained DNA samples and ear measurements from a small group of house-elves to conduct a preliminary analysis (prior to submitting a grant application to the Ministry of Magic) and she would like you to conduct the analysis for her. She has placed the file on the web for you to download, located ==> [here](https://nyu-cds.github.io/courses/data/houseelf_earlength_dna_data.csv) <==.

You might be able to do this analysis by hand in Excel, but counting all of those bases would be a lot of work, and besides, Dr. Granger seems to always get funded, which means that you’ll be doing this again soon with a much larger dataset. So, you decide to write a script so that it will be easy to do the analysis again.

Write a Python script that:

1. Imports the data into a data frame
2. Loops over the rows in the data frame
3. For each row in the dataset, checks to see if the ear length is large (>10 cm) or small (<=10 cm) and determines the GC-content of the DNA sequence (i.e., the percentage of bases that are either G or C)
4. Stores this information in a **new data frame** where the first column has the ID for the individual, the second column contains the string ‘large’ or the string ‘small’ depending on the size of the individuals ears, and the third column contains the GC content of the DNA sequence.
5. Prints the average GC-content for both large-eared elves and small-eared elves to the screen.
6. Exports the table of individual level GC values to a CSV (comma delimited text) file titled grangers_analysis.csv.

**BONUS**: Write functions that perform each of the steps above

[Source for problem](https://nyu-cds.github.io/courses/exercises/Basic-python-2/)

# Solution - variant 1

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Request 1:

Imports the data into a data frame

##### my file location

```
# This is formatted as code
```



/content/drive/MyDrive/ddds-cohort-20/Modules/Module_3_SQL/Exercises/houseelf_earlength_dna_data.csv

In [ ]:
# Paste your copied path here (it will look similar to this)
file_path = "/content/drive/MyDrive/ddds-cohort-20/Modules/Module_3_SQL/Exercises/houseelf_earlength_dna_data.csv"

# Load the data natively from your Drive
df = pd.read_csv(file_path)

# Inspect the column names to see what Dr. Granger named them
print(df.columns.tolist())
print(df.head(11))

['id', 'earlength', 'dnaseq']
    id  earlength                                             dnaseq
0  17A        5.1  CCGCATCTTGACTTAACTGACATATTACCATAGATGACTAGCCATG...
1  24P        7.5  GCTATGACTTGCTTAGCTACGTATGAAGGAAGAAACTTTTGTGTAT...
2  09Q       12.2  CCGCCGATTGATACAGGGGACGGTGACGTCGTCATAGATTCGGCAC...
3  65Y        9.9  GCAGGAGAAGTTCTTAACCTTCTCGTAGGACGTCAACCTATTCTTT...
4  19N       10.0  TCTTCATCCTTATCAAAGTTTGGAGTCAATGATCAGGATTATTGCC...
5  92K       14.6  ACCGATGGACAATGATTCGGGTAGCACCAGGAGTCCGTAGCGCGTG...
6  33W        8.2  CAGCTTGACTCGGTCTGTTAGGCCACGATTACGTGAGTTAGGGCTC...
7  98C       17.8  CTGCATGCTAGGTTGACACGCCTGCACTGCTCGAAGAAAATATGCG...
8  75G        9.4  CTTATTTAGATAACATGATTAGCCGAAGTTGTACGGGATATCCACC...
9  88Q       11.3  GATTGCTCGCACATGAGCAAAACGGTAGAGCGTCACTTTCAGCCCT...

In [ ]:
df.shape

(10, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     object
 1   earlength  10 non-null     float64
 2   dnaseq     10 non-null     object
dtypes: float64(1), object(2)
memory usage: 372.0+ bytes

In [ ]:
df.describe()

       earlength
count   10.00000
mean    10.60000
std      3.63318
min      5.10000
25%      8.50000
50%      9.95000
75%     11.97500
max     17.80000

### Request 2 and 3:

Loops over the rows in the data frame - This was replaced with two function: one of the functions calculates the GC content, the other function converts the length of the ears in a string, large or small depending on the size.


For each row in the dataset, checks to see if the ear length is large (>10 cm) or small (<=10 cm) and determines the GC-content of the DNA sequence (i.e., the percentage of bases that are either G or C)

In [ ]:
# 1. Define a function to calculate GC content.
def calculate_gc_content(dna_sequence):
    """Calculates the percentage of G and C bases in a DNA string."""
    dna = dna_sequence.upper()
    g_count = dna.count('G')
    c_count = dna.count('C')
    gc_content = ((g_count + c_count) / len(dna)) * 100
    return gc_content
def categorize_ear_length(length):
    if length > 10:
        return 'large'   # Converts numbers > 10 to the string 'large'
    else:
        return 'small'   # Converts numbers <= 10 to the string 'small'
# 2. Create the new column using .apply()
# (Make sure 'dna' matches the exact name of your DNA column)
df['gc_content'] = df['dnaseq'].apply(calculate_gc_content)
# This is the step that converts the numbers into 'large' or 'small'
df['ear_size'] = df['earlength'].apply(categorize_ear_length)
# 3. View the updated dataframe
print(df.head(11))
df

    id  earlength                                             dnaseq  \
0  17A        5.1  CCGCATCTTGACTTAACTGACATATTACCATAGATGACTAGCCATG...
1  24P        7.5  GCTATGACTTGCTTAGCTACGTATGAAGGAAGAAACTTTTGTGTAT...
2  09Q       12.2  CCGCCGATTGATACAGGGGACGGTGACGTCGTCATAGATTCGGCAC...
3  65Y        9.9  GCAGGAGAAGTTCTTAACCTTCTCGTAGGACGTCAACCTATTCTTT...
4  19N       10.0  TCTTCATCCTTATCAAAGTTTGGAGTCAATGATCAGGATTATTGCC...
5  92K       14.6  ACCGATGGACAATGATTCGGGTAGCACCAGGAGTCCGTAGCGCGTG...
6  33W        8.2  CAGCTTGACTCGGTCTGTTAGGCCACGATTACGTGAGTTAGGGCTC...
7  98C       17.8  CTGCATGCTAGGTTGACACGCCTGCACTGCTCGAAGAAAATATGCG...
8  75G        9.4  CTTATTTAGATAACATGATTAGCCGAAGTTGTACGGGATATCCACC...
9  88Q       11.3  GATTGCTCGCACATGAGCAAAACGGTAGAGCGTCACTTTCAGCCCT...

   gc_content ear_size
0        41.0    small
1        39.0    small
2        57.0    large
3        40.0    small
4        36.0    small
5        62.0    large
6        52.0    small
7        63.0    large
8        47.0    small
9        52.0    large

,id,earlength,dnaseq,gc_content,ear_size
0,17A,5.1,CCGCATCTTGACTTAACTGACATATTACCATAGATGACTAGCCATG...,41.0,small
1,24P,7.5,GCTATGACTTGCTTAGCTACGTATGAAGGAAGAAACTTTTGTGTAT...,39.0,small
2,09Q,12.2,CCGCCGATTGATACAGGGGACGGTGACGTCGTCATAGATTCGGCAC...,57.0,large
3,65Y,9.9,GCAGGAGAAGTTCTTAACCTTCTCGTAGGACGTCAACCTATTCTTT...,40.0,small
4,19N,10.0,TCTTCATCCTTATCAAAGTTTGGAGTCAATGATCAGGATTATTGCC...,36.0,small
5,92K,14.6,ACCGATGGACAATGATTCGGGTAGCACCAGGAGTCCGTAGCGCGTG...,62.0,large
6,33W,8.2,CAGCTTGACTCGGTCTGTTAGGCCACGATTACGTGAGTTAGGGCTC...,52.0,small
7,98C,17.8,CTGCATGCTAGGTTGACACGCCTGCACTGCTCGAAGAAAATATGCG...,63.0,large
8,75G,9.4,CTTATTTAGATAACATGATTAGCCGAAGTTGTACGGGATATCCACC...,47.0,small
9,88Q,11.3,GATTGCTCGCACATGAGCAAAACGGTAGAGCGTCACTTTCAGCCCT...,52.0,large

### Request 4:

Stores this information in a new data frame where the first column has the ID for the individual, the second column contains the string ‘large’ or the string ‘small’ depending on the size of the individuals ears, and the third column contains the GC content of the DNA sequence.

In [ ]:
#creating a new df with only the information I need

grangers_df = df[['id', 'ear_size', 'gc_content']].copy()

# Verify your new isolated DataFrame
grangers_df

    id ear_size  gc_content
0  17A    small        41.0
1  24P    small        39.0
2  09Q    large        57.0
3  65Y    small        40.0
4  19N    small        36.0
5  92K    large        62.0
6  33W    small        52.0
7  98C    large        63.0
8  75G    small        47.0
9  88Q    large        52.0

### Request 5:

Prints the average GC-content for both large-eared elves and small-eared elves to the screen.

In [ ]:
#printing the average GC-content for small and large eared elves
# Group by the ear size and calculate the average GC content
averages = grangers_df.groupby('ear_size')['gc_content'].mean()
print("\n--- Average GC-Content by Ear Size ---")
averages

--- Average GC-Content by Ear Size ---

ear_size
large    58.5
small    42.5
Name: gc_content, dtype: float64

### Request 6:


Exports the table of individual level GC values to a CSV (comma delimited text) file titled grangers_analysis.csv.

In [ ]:
# It saves the file directly to working directory in Colab
grangers_df.to_csv('grangers_analysis.csv', index=False)
print("\nFile successfully exported as 'grangers_analysis.csv'")

File successfully exported as 'grangers_analysis.csv'

In [ ]:
# to save the file into my Google drive:
# my path is below:
# /content/drive/MyDrive/ddds-cohort-20/Modules/Module_3_SQL/Exercises/grangers_analysis.csv

grangers_df.to_csv('grangers_analysis.csv', index=False)
print("\nFile successfully exported as '/content/drive/MyDrive/ddds-cohort-20/Modules/Module_3_SQL/Exercises/grangers_analysis.csv'")

File successfully exported as '/content/drive/MyDrive/ddds-cohort-20/Modules/Module_3_SQL/Exercises/grangers_analysis.csv'